# pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- script: sudo npm i -g serverless
  displayName: 'NPM'

- script: serverless config credentials --provider aws --key $(AWS_ACCESS_KEY_ID) --secret $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Creditinals '

# couldn't set token via config credentials, so just adding it to end of file
- script: echo $(AWS_SESSION_TOKEN) | tee -a ~/.aws/credentials
  displayName: 'Token '

#- script: sudo cat ~/.aws/credentials

- script: serverless deploy